name: ACTIONS

on: push

jobs:
  
  build:  
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Compile Java Classes
        run: gradle build
        
  test-pacman-consume:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Test pacman-consume functionality
        run: gradle test --tests TestPacManConsume

  test-ghost-attack:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Test pacman-consume functionality
        run: gradle test --tests TestGhostAttack

  test-pacman-consume:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Test pacman-consume functionality
        run: gradle test --tests TestMapEatCookie

  test-pacman-move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Test Pacman Move
        run: |
          cd Projects/P2
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManMove
  
  test-ghost-move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Test Ghost Move
        run: |
          cd Projects/P2
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostMove
  
  test-map-getloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Test Map getLoc
        run: |
          cd Projects/P2
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapGetLo
  
  test-pacman-range:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Test Pacman In Range
        run: |
          cd Projects/P2
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManInRange
  
  test-ghost-range:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Test Ghost In Range
        run: |
          cd Projects/P2
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostInRange
  
  test-map-attack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Test Map attack
        run: |
          cd Projects/P2
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapAttack

  test-ghost-get_valid_moves:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Test ghost-get_valid_moves functionality
        run: gradle test --tests TestGhostValidMoves

  test-pacman-get_valid_moves:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Test pacman-get_valid_moves functionality
        run: gradle test --tests TestPacManValidMoves

  test-map-move:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Test map-move functionality
        run: gradle test --tests TestMapMove

