name: ACTIONS

on: push

jobs:
  
  build:  
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Compile Java Classes
        run: gradle build

    test-pacman-range:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            distribution: 'zulu'
            java-version: '8'
        - name: Test Pacman In Range
          run: |
            cd Projects/P2
            javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
            java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManInRange
    test-ghost-range:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            distribution: 'zulu'
            java-version: '8'
        - name: Test Ghost In Range
          run: |
            cd Projects/P2
            javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
            java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostInRange
    test-map-attack:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            distribution: 'zulu'
            java-version: '8'
        - name: Test Map attack
          run: |
            cd Projects/P2
            javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
            java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapAttack

